target: is_recid

features:
  binary: []
  categorical:
    - sex
    - race
    - c_charge_degree
  numerical:
    - age
    - juv_fel_count
    - juv_misd_count
    - juv_other_count
    - priors_count
    - jailtime
  ordinal: []
  exclude: []

preprocessing:
  missing_value_codes: {}