target: suicide

features:
  categorical:
    - attacktype1
    - attacktype2
    - attacktype3
    - weaptype1
    - weaptype2
    - weaptype3
    - weaptype4
    - targtype1
    - targtype2
    - targtype3
    - ransom
  numerical:
    - nkill
    - nwound
    - nhostkid
    - nkillter
    - nwoundte
    - nperps
    - nperpcap
    - nkillus
    - nwoundus
    - nhostkidus
    - ndays
    - nhours
    - nreleased
    - propvalue
    - ransomamt
    - ransomamtus
    - ransompaid
    - ransompaidus
  ordinal: []
  exclude:
    - alternative
    - alternative_txt
    - city
    - claim2
    - claim3
    - claimed
    - claimmode
    - claimmode2
    - claimmode3
    - compclaim
    - country
    - country_txt
    - crit1
    - crit2
    - crit3
    - doubtterr
    - latitude
    - longitude
    - natlty1
    - natlty2
    - natlty3
    - provstate
    - region
    - region_txt
    - success
    - targsubtype1
    - targsubtype2
    - targsubtype3
    - vicinity
    - weapsubtype1
    - weapsubtype2
    - weapsubtype3
    - weapsubtype4
    - INT_ANY
    - INT_IDEO
    - INT_LOG
    - INT_MISC
    - addnotes
    - approxdate
    - attacktype1_txt
    - attacktype2_txt
    - attacktype3_txt
    - claimmode2_txt
    - claimmode3_txt
    - claimmode_txt
    - corp1
    - corp2
    - corp3
    - dbsource
    - divert
    - eventid
    - extended
    - gname
    - gname2
    - gname3
    - gsubname
    - gsubname2
    - gsubname3
    - guncertain1
    - guncertain2
    - guncertain3
    - hostkidoutcome
    - hostkidoutcome_txt
    - iday
    - imonth
    - individual
    - ishostkid
    - iyear
    - kidhijcountry
    - location
    - motive
    - multiple
    - natlty1_txt
    - natlty2_txt
    - natlty3_txt
    - propcomment
    - property
    - propextent
    - propextent_txt
    - ransomnote
    - related
    - resolution
    - scite1
    - scite2
    - scite3
    - specificity
    - summary
    - target1
    - target2
    - target3
    - targsubtype1_txt
    - targsubtype2_txt
    - targsubtype3_txt
    - targtype1_txt
    - targtype2_txt
    - targtype3_txt
    - weapdetail
    - weapsubtype1_txt
    - weapsubtype2_txt
    - weapsubtype3_txt
    - weapsubtype4_txt
    - weaptype1_txt
    - weaptype2_txt
    - weaptype3_txt
    - weaptype4_txt

preprocessing:
  missing_value_codes: {}